import React, { useState } from 'react';
import {
  SafeAreaView,
    View,
      Text,
        TextInput,
          Pressable,
            StyleSheet,
            } from 'react-native';
            import { router } from 'expo-router';
            import Admin from '../admin/Admin';

            export default function AdminAccess() {
              const [password, setPassword] = useState('');
                const [accessGranted, setAccessGranted] = useState(false);
                  const [error, setError] = useState('');

                    const handleAccess = () => {
                        if (password === 'Nathan') {
                              setError('');
                                    setAccessGranted(true);
                                        } else {
                                              setError('Password non corretta');
                                                    setPassword('');
                                                        }
                                                          };

                                                            if (accessGranted) {
                                                                return <Admin />;
                                                                  }

                                                                    return (
                                                                        <SafeAreaView style={styles.container}>
                                                                              <View style={styles.card}>
                                                                                      <Text style={styles.icon}>🔐</Text>

                                                                                              <Text style={styles.title}>
                                                                                                        Area proprietario
                                                                                                                </Text>

                                                                                                                        <Text style={styles.subtitle}>
                                                                                                                                  Inserisci la password per accedere alla gestione di SA DOMMU MEA.
                                                                                                                                          </Text>

                                                                                                                                                  <TextInput
                                                                                                                                                            style={styles.input}
                                                                                                                                                                      value={password}
                                                                                                                                                                                onChangeText={setPassword}
                                                                                                                                                                                          placeholder="Password"
                                                                                                                                                                                                    placeholderTextColor="#999"
                                                                                                                                                                                                              secureTextEntry
                                                                                                                                                                                                                        autoCapitalize="none"
                                                                                                                                                                                                                                  onSubmitEditing={handleAccess}
                                                                                                                                                                                                                                          />

                                                                                                                                                                                                                                                  {error !== '' && (
                                                                                                                                                                                                                                                            <Text style={styles.error}>
                                                                                                                                                                                                                                                                        {error}
                                                                                                                                                                                                                                                                                  </Text>
                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                  <Pressable
                                                                                                                                                                                                                                                                                                            style={styles.button}
                                                                                                                                                                                                                                                                                                                      onPress={handleAccess}
                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                        <Text style={styles.buttonText}>
                                                                                                                                                                                                                                                                                                                                                    ACCEDI
                                                                                                                                                                                                                                                                                                                                                              </Text>
                                                                                                                                                                                                                                                                                                                                                                      </Pressable>

                                                                                                                                                                                                                                                                                                                                                                              <Pressable
                                                                                                                                                                                                                                                                                                                                                                                        style={styles.backButton}
                                                                                                                                                                                                                                                                                                                                                                                                  onPress={() => router.back()}
                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.backText}>
                                                                                                                                                                                                                                                                                                                                                                                                                                ← Torna indietro
                                                                                                                                                                                                                                                                                                                                                                                                                                          </Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Pressable>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                              const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: '#F7F3EC',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    card: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: '#FFFFFF',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: 25,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    icon: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 48,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 27,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#2F4638',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        subtitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: '#777064',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    lineHeight: 21,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    input: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: '#F7F3EC',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                paddingHorizontal: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    paddingVertical: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: '#2F4638',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    error: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: '#A35CAF',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '700',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginBottom: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        button: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: '#2F4638',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    paddingVertical: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginTop: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                buttonText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: '#FFFFFF',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontWeight: '900',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backButton: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        marginTop: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                color: '#2F4638',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: '700',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });